### ISSUE TITLE
If vites config contains `defineConfig` with callback, then SSR is broken

### ISSUE THREAD

**Issue by PredokMiF** [fastify/fastify-vite#111]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.17.0

### Plugin version

4.0.0

### Node.js version

16.18.1

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10 Pro (21H2)

### Description

In `vite.config.js` I need to generate config for different goals. `vite` [can help with this case](https://vitejs.dev/config/#conditional-config) and front build is Ok, but when I start http-server with the plugin - it fails, cause in next code
https://github.com/fastify/fastify-vite/blob/568e178a10768211944bfc1aaf6e57a6a091693d/packages/fastify-vite/config.js#L173
we try to make `Object.assign(<function>, <object>)`, where `<function>` is config-function from `vite.config.js`

### Steps to Reproduce

1. Get any react SSR example (not SPA) like https://github.com/fastify/fastify-vite/tree/dev/examples/react-hydration
2. Open [vite.config.js](https://github.com/fastify/fastify-vite/blob/dev/examples/react-hydration/vite.config.js)
3. Modify export like this
```js
import { defineConfig } from 'vite'
//...
export default defineConfig((config) => {
    return ({ root, plugins })
})
```

### Expected Behavior

No issue

**Comment by galvez** [comment]
Think is already fixed, need to add a test and push out the new release. Will double check.

**Comment by PredokMiF** [comment]
This is great news because this bug breaks my build and I had to add a lot of hacks. I'm really looking forward to the release.

**Comment by PredokMiF** [comment]
In which branch can I see the fixed code
