### ISSUE TITLE
Serve static assets from ssr builds in production mode

### ISSUE THREAD

**Issue by ajaishankar** [fastify/fastify-vite#116]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Vite has the option to generate assets for ssr builds.

https://main.vitejs.dev/config/build-options#build-ssremitassets

Currently @fastify/vite only serves client assets, could it be updated to also serve ssr build assets?

Something like:

```js
  await this.scope.register(async function staticContext (scope) {
    await scope.register(FastifyStatic, {
      root: [resolve(clientDist, assetsDir), resolve(serverDist, assetsDir)],
      prefix: `/${assetsDir}`
    })
  })
```

**Comment by galvez** [comment]
Yep, that sounds like a reasonable thing to do. Can you open a PR with that change? I'll review and test then.

**Comment by ajaishankar** [comment]
@galvez Have opened PR https://github.com/fastify/fastify-vite/pull/121

Was not sure about how to run the tests though...
