### ISSUE TITLE
@fastify/vue Smart Import doesn't resolve path in windows

### ISSUE THREAD

**Issue by agorem** [fastify/fastify-vite#144]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.26.2

### Plugin version

6.0.6

### Node.js version

20.10.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Description

Hi,

I have downloaded in my Win11 laptop the starter project vue-kitchensink.

After installing the node modules, when I run npm run dev I get loads of errors related with the Smart import URL resolution :

Below you have some examples:   

12:54:15 [vite] Pre-transform error: Failed to load url **./$_dev/$_js_projects/vue-kitchensink/C:/$_dev/$_js_projects/vue-kitchensink/client/pages/index.vue** (resolved id: ./$_dev/$_js_projects/vue-kitchensink/C:/$_dev/$_js_projects/vue-kitchensink/client/pages/index.vue) in /:routes.js. Does the file exist?
12:54:15 [vite] Pre-transform error: Failed to load url ./$_dev/$_js_projects/vue-kitchensink/C:/$_dev/$_js_projects/vue-kitchensink/client/pages/form/[id].vue (resolved id: ./$_dev/$_js_projects/vue-kitchensink/C:/$_dev/$_js_projects/vue-kitchensink/client/pages/form/[id].vue) in /:routes.js. Does the file exist?     
12:54:15 [vite] Pre-transform error: Failed to load url ./$_dev/$_js_projects/vue-kitchensink/C:/$_dev/$_js_projects/vue-kitchensink/client/pages/client-only.vue (resolved id: ./$_dev/$_js_projects/vue-kitchensink/C:/$_dev/$_js_projects/vue-kitchensink/client/pages/client-only.vue) in /:routes.js. Does the file exist? 

Any help??

### Steps to Reproduce

Just make a fresh starter install and run

### Expected Behavior

The resolved ID path in my project should be: C:/$_dev/$_js_projects/vue-kitchensink/client/** and not *./$_dev/$_js_projects/vue-kitchensink/C:/$_dev/$_js_projects/vue-kitchensink/client/**

**Comment by agorem** [comment]
Hi,
I think I have located the bug
The problem is in **fastify > vue > plugin.cjs.**

`
const { readFileSync, existsSync } = require('fs')
const { dirname, join, resolve } = require('path')
const { fileURLToPath } = require('url')

function viteFastifyVue (config = {}) {  
  const prefix = /^\/:/
  const routing = Object.assign({
    globPattern: '/pages/**/*.vue',   // The right value is './pages/**/*.vue'
    paramPattern: /\[(\w+)\]/,
  }, config)`

Kind regards...Antonio

**Comment by agorem** [comment]
In virtual>layout.vue there is the same problem in the layout pattern:
const appLayouts = import.meta.glob('/layouts/*.vue', { eager: true })

**Comment by Shyam-Chen** [comment]
This is the known issue. (https://github.com/fastify/fastify-vite/pull/141)

**Comment by agorem** [comment]
Thanks @Shyam-Chen,
I'll wait for the update.
Meanwhile, I assume that I can bypass the problem using my own routes,js.

**Comment by galvez** [comment]
Yes you can!

**Comment by justekoro** [comment]
hi, does not seem to be fixed yet?
