### ISSUE TITLE
How to config fastify-vite in a Electron Vite project

### ISSUE THREAD

**Issue by zoffyzhang** [fastify/fastify-vite#145]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hello! I'm trying to host a fastify server within the Electron main process and make use of the hot reload feature provided by fastify-vite. However, I'm encountering issues getting it to work as expected. 
Could you provide an example of integrating fastify-vite with [Electron Vite template](https://www.electronforge.io/templates/vite)? This would be immensely helpful.

**Comment by Shyam-Chen** [comment]
This requires converting the build output into a Static Site Generator (SSG).
