### ISSUE TITLE
Fastify v5.0 CLI issue

### ISSUE THREAD

**Issue by NathanaelA** [fastify/fastify-vite#170]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

5.0.0

### Plugin version

7.0.0-alpha

### Node.js version

20.17

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

22.04

### Description

With the PR #169 changes, I am able to run fastify/vite with fastify v5 properly using a standalone server.js file and when running it from node.    (i.e. `node server` or `npm start` in the example directory) 

If I attempt to run it using `npm run dev` which maps to `fastify start -w -l info -P dev-server.js` then the server gets into a weird loop where it keeps trying to re-add the `vite-svelte.js` plugin file.

```
'use strict';

import { fastifyPlugin as fp } from 'fastify-plugin';
import path from "node:path";
import { render } from 'svelte/server';
import fastifyVite from "@fastify/vite";

const root = path.resolve(import.meta.dirname, '..')

export default fp(async function (fastify, opts) {
    console.log("isDev", fastify.config.isDev)

    await fastify.register(fastifyVite, {
        dev: !!fastify.config.isDev,
        root: root,
        createRenderFunction(options) {
            return () => {
                return {element: render(options.Page).body};
            }
        }
    });

    fastify.get('/client/', (req, reply) => {
        reply.type('text/html').code(200);
        return reply.html()
    })

    await fastify.vite.ready();
    console.log('Vite is ready');
});
```

1. The `IsDev: true` reprints about every 30ms, and `Vite is ready` is never printed.   
2. A new vite.config.js.timestamp-xxxxxxxxxxxxxxxx is created each time it loops by the @fastify/vite plugin.
3. If I remove the `await fastify.vite.ready();` from the `plugins/vite-svelte.js` file the server starts up properly and can server other routes (i.e. the default / route) , but the `/client/` route is broken because `reply.html()` isn't available...

The example MRE, has everything configured and  both server & server-dev should work after the `npm i`  

### Link to code that reproduces the bug

https://github.com/NathanaelA/fastify-vite-issue-1

### Expected Behavior

It starts up the Vite server properly....

**Comment by galvez** [comment]
The `client` folder needs to be ignored by the `fastify-cli` hot reload watcher, try:

```sh
FASTIFY_IGNORE_WATCH=client npm run dev
```

You can also use a config file for this with `fastify-cli`.

**Comment by galvez** [comment]
Further

**Comment by galvez** [comment]
Let me know if that works for you.

**Comment by NathanaelA** [comment]
No, that isn't it -- but finding out about the `client` folder will be very helpful once I start messing with it...  So thanks.

I was just coming to tell you the actual issue is caused by fastiy-cli seeing the newly created "vite.config.js.timestampxxxx" file, it triggers it to restart, causing vite to generate another vite.config.js.timestampxxxx to be created and so it basically goes into a loop of create the new timestamp file, restart, create, restart....   

 It hit me about 30 minutes ago that it was generating new JS files, and I bet the watcher was restarting....

What I tested before seeing your idea about the client is you can pass:
--ignore-watch='node_modules .git vite.config.*' to it to ignore node_modules, the .git folder and any vite.config.* files.  :grinning:      

That  fixed the issue.   I'll add "client" to my list.

So my cli is now: `fastify start -w --ignore-watch='node_modules client .git vite.config.*' -l info -P dev-server.js` 

For anyone in the future who runs into vite generating the timestamp files, you need to ignore them...

**Comment by galvez** [comment]
Thank you for that investigation — this should go into the documentation suite soon.
