### ISSUE TITLE
Vanilla Example?

### ISSUE THREAD

**Issue by ivanjeremic** [fastify/fastify-vite#21]
Hello, Very nice work, thanks for it. 

Nice that in the Examples folder there are examples for react & vue is it possible to get a super minimal example to have exactly what these two examples do but without framework at all just for better understanding?

Thanks

**Comment by galvez** [comment]
@ivanjeremic v3 is out with vanilla examples for Vue and React! New API too, lots of changes, more flexibility.

Might want to check it out again.
