### ISSUE TITLE
Move renderer dependencies to peerDependencies

### ISSUE THREAD

**Issue by sionzee** [fastify/fastify-vite#22]
You have specified vue version in package.json without giving an ability to change it. Please move the vue dependency to peerDependencies. 

This is applied to: @vue/compiler-sfc, @vue/server-renderer, vue, vue-router. 

Please move there @vitejs/plugin-vue and @vitejs/plugin-vue-jsx too. 

At the moment I'm using workaround via yarn resolutions.

```json
  "resolutions": {
    "vue": "^3.2.12",
    "@vue/compiler-sfc": "^3.2.12",
    "@vue/server-renderer": "^3.2.12",
    "vite": "^2.5.10",
    "vue-router": "^4.0.11",
    "@vitejs/plugin-vue": "1.8.1",
    "@vitejs/plugin-vue-jsx": "1.1.8"
  }
```

**Comment by galvez** [comment]
Thanks @sionzee — looking into this now.

**Comment by galvez** [comment]
Renderer adapter packages are deprecated for now, but that'll be the case when they're revived as part of Fastify DX.

See the new README for more info.
