### ISSUE TITLE
Support <script setup>

### ISSUE THREAD

**Issue by lukeeno** [fastify/fastify-vite#28]
Hi,
I may wrong, but

```vue
<script setup>
export const path = '/about'
</script>
```

does not seem to be working. Is there a way to make it work? `<script setup>` is recommended way to use components since version 3.2. Something like

```vue
<script setup>
import { definePath } from 'fastify-vite'

definePath('/about')
</script>
```

But I don't know if this would be suitable for other exported variables.

**Comment by galvez** [comment]
Hm, I like the idea — in the meantime, this works:

```
<script>
export const path = '/about'
</script>

<script setup>
...
</script>
```

See [here](https://v3.vuejs.org/api/sfc-script-setup.html#usage-alongside-normal-script).

**Comment by SuslegStyle** [comment]
@lukeeno As far as I understood `script setup` documentation, the simple
```<script setup>
const path = '/';
...
</script>

should work for you. There is no need to export something. Any defined constanct is exports automatically. (https://v3.vuejs.org/api/sfc-script-setup.html#top-level-bindings-are-exposed-to-template)

**Comment by lukeeno** [comment]
@SuslegStyle I think your example only "exports" variable to the template, but I need to export it from the module. To do so, I ought to use the syntax in previous comment.

**Comment by galvez** [comment]
Routing has changed in fastify-vite v3 and is now completely configurable. See the new README for details. 

Would love to see a Vue example contributed that supports `<script setup>`!
