### ISSUE TITLE
Route management

### ISSUE THREAD

**Issue by mhf-ir** [fastify/fastify-vite#29]
is there any option/api for managment routes?

How deal with it. 
Routs basicually need baseURL, named route for generate url base on parameters and etc.

Thanks for your awesome project bwt

**Comment by haikyuu** [comment]
Thought I'd shime in here to ask my question: How do you integrate server side routing with client-side routing (as mentioned in the README)?

**Comment by galvez** [comment]
Answer to this came late but it's here: https://fastify-vite.dev/guide/router-integration
