### ISSUE TITLE
[Bug] 2.3.0 not building

### ISSUE THREAD

**Issue by davidmeirlevy** [fastify/fastify-vite#46]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.23.1

### Plugin version

2.3.0

### Node.js version

14.7 + 15.x

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

tried on mac, linux (both github actions and circleci)

### Description

Running `node index.ms build` is running the server and doesn't generate the dist directory.

### Steps to Reproduce

1. use 2.2.4 - run `node index.ms build` - will work.
2. re-install the plugin at version 2.3.0 - fastify server will run, dist folder will not be created

### Expected Behavior

dist folder should be created with relevant files, and the process should be exited with code 0.

**Comment by galvez** [comment]
Did you see the release notes for `v2.3.0`? There's a breaking change related to it.

**Comment by davidmeirlevy** [comment]
@galvez I have 2 branches that the only difference between them is the version of fastify-vite.
this one has 2.2.4:
https://github.com/greenpress/greenpress/pull/135 (it's a monorepo, so look for `apps/front-ssr`).

the second with version 2.3.0:
https://github.com/greenpress/greenpress/pull/137 (same folder).

**Comment by davidmeirlevy** [comment]
> Did you see the release notes for `v2.3.0`? There's a breaking change related to it.

no, I didn't...  you just release 2.2.4 yesterday, so I haven't figured out there are so many publishes until today :)

**Comment by davidmeirlevy** [comment]
@galvez looks like it's working after i changed `await app.vite.ready()` to: `await app.vite.commands()` on the `index.mjs`.
I'll wait for circleci + github actions results.
