### ISSUE TITLE
getPayload should be tree-shaked from client dist

### ISSUE THREAD

**Issue by davidmeirlevy** [fastify/fastify-vite#50]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Inside my component file, when I export the `getPayload` function, it should be tree-shaked from the client code `dist` files.

Also, to tree-shake everything that is only used by the `getPayload` functions (such as backend libraries).

### Motivation

to reduce the bundle size and to remove, and not expose code that runs on the backend.

### Example

I managed to create a workaround that actually works in here:
https://github.com/greenpress/greenpress/blob/dynamic-front-ssr/apps/front-ssr/views/index.vue

**Note**: it's not tree-shaking the `sdk` import that is only used by the `getPayload`.

As you can see, I wrapped the original getPayload with a conditional `import.meta.env.SSR`.
I also passed `true` as a value to the `useHydration` hook in order to make it call the payload even though I don't have the original function.

**Comment by galvez** [comment]
@davidmeirlevy I was gonna work on a little something for this but [@egoist](https://github.com/egoist) beat me to it.

https://github.com/egoist/vite-plugin-remove-exports

Maybe we could give it a shot using it.

**Comment by davidmeirlevy** [comment]
I'll look into it and send a demonstration.
