### ISSUE TITLE
Compile server dist file to mjs instead of cjs

### ISSUE THREAD

**Issue by davidmeirlevy** [fastify/fastify-vite#51]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

compile the server app into `mjs` file instead of `cjs`.

### Motivation

`mjs` has top-level `await` like the browser also has, and it's much more consistent.

### Example

When I ran the app on dev mode, I managed to write a line like `await import("my-third-party-dep")` on a file's top-level, but this line failed to compile (the build failed).

When I tried to use something like:
```
// this all area is removed from the client dist anyway:
if(import.meta.env.SSR) {
  require("my-third-party-dep")  
}
```
It didn't run for both dev and build, with the error:
`ReferenceError: require is not defined`

**Comment by galvez** [comment]
I'm afraid this is not possible anymore as the latest version of Vite went full ESM and everything's prefered to be ESM now. The workaround is to use `createRequire()` from `node:module`.
