### ISSUE TITLE
Missing monorepo scripts

### ISSUE THREAD

**Issue by micheleriva** [fastify/fastify-vite#59]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Hi!
While trying to contribute to the project, I've noticed that it uses the `packages` folder as specified in the workspaces docs (https://docs.npmjs.com/cli/v7/using-npm/workspaces), but some links in the main `package.json` are missing:

```js
{
  ...
  "workspaces": [
    "fastify-vite",
    "fastify-vite-react",
    "fastify-vite-vue"
  ],
  ...
}
```

that would help enforce dependency versions consistency amongst different packages and also enables a series of helpful npm scripts to manage the monorepo.

Is there a specific reason why the project is not set up as an npm monorepo? If not, I'd be glad to help with the setup!

**Comment by Shyam-Chen** [comment]
This project is built using `pnpm` for managing a Monorepo.
