### ISSUE TITLE
Have you seen vite-plugin-node can you do something similar for HMR?

### ISSUE THREAD

**Issue by frog-o** [fastify/fastify-vite#68]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

The main reason I would like to use  vite is HMR which your plugin does not do.  I like the fact you are trying to keep thing simple which using vite and   [vite-plugin-node](https://www.npmjs.com/package/vite-plugin-node) does not do.
That also the reason i like yarn3 IMHO it look simpler then npm but sadly a lot of programs crashes with it.

- what the difference between [vite-plugin-node](https://www.npmjs.com/package/vite-plugin-node)  and yours beside running on fastify and not be able to HMR 
- is there a reason you are make a plugin for fastify? 
- would a rewrite be justifiable?
- I see this is part of fastify so can't you fix this limitation you motion in the FAQ?

The reason I am asking ,I been trying to use your plugin but everything keep crashing and wounding if I should come back later 

first with missing dependencies 
I had to add a lot those from dependencies.md and then  i had to run 
npm install vue-router@4

And it still crashes with 

[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: Server rendering context not provided. Make sure to only call useSSRContext() conditionally in the server build.
[Vue warn]: Unhandled error during execution of setup function 
  at <Client>
TypeError: Cannot read properties of undefined (reading 'modules')
    at _sfc_main.setup (@app/client.vue:66:16)
    at callWithErrorHandling (/home/pi/system-admin/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6582:22)
    at setupStatefulComponent (/home/pi/system-admin/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6208:29)
    at setupComponent (/home/pi/system-admin/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6164:11)
    at renderComponentVNode (/home/pi/system-admin/node_modules/fastify-vite-vue/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:198:17)
    at /home/pi/system-admin/node_modules/fastify-vite-vue/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:456:30
    at Generator.next (<anonymous>)
    at /home/pi/system-admin/node_modules/fastify-vite-vue/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:30:71
    at new Promise (<anonymous>)
    at __awaiter (/home/pi/system-admin/node_modules/fastify-vite-vue/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:26:12)
{"level":30,"time":1644762988964,"pid":17513,"hostname":"frog64debain","reqId":"req-1","res":{"statusCode":500},"responseTime":254.15144681930542,"msg":"request completed"}

I thought it might be the fact i trying to use yarn( i tried all kind of version) then  i tried to use npm still have this error 

running on my raspberry pi with latest version of node.  Vite run fine  

- I thought you might have not seen **vite-plugin-node** and it might be helpful in your endeavor

**Comment by sync** [comment]
New version does hmr, just tested it with React

**Comment by bskimball** [comment]
I get this with Vue ```ReferenceError: __VUE_HMR_RUNTIME__ is not defined```

**Comment by sync** [comment]
@galvez  let me know if you would like a PR with those changes

**Comment by galvez** [comment]
@sync Oh, that is a good catch! Would love a PR, for sure!

**Comment by sync** [comment]
nice, have a look at this PR: https://github.com/fastify/fastify-vite/pull/78

**Comment by bskimball** [comment]
Upgrading to 3.0.0-beta.21 worked for me. Thanks for the quick fix.

**Comment by galvez** [comment]
Closed via #78
