### ISSUE TITLE
Quickstart of React example failed in start script

### ISSUE THREAD

**Issue by lbittencurt** [fastify/fastify-vite#75]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.29.0

### Node.js version

16.x

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

11.6.2

### Description

I tried to use the QuickStart example with React, I've followed the steps as per the docs:
1. create a folder
2. install all dependencies
3. create a app.mjs file according with the snippet
4. create a index.jsx file in views folder

When I run the command "node app.mjs" I have the following response:
```
❯ node app.mjs                                                        
file:///Users/lucasbittencurt/www/ssr-vite/app.mjs:9
await app.vite.commands()
               ^

TypeError: app.vite.commands is not a function
    at file:///Users/lucasbittencurt/www/ssr-vite/app.mjs:9:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)```

### Steps to Reproduce

Follow the quickstart for React with node version 16.x 

### Expected Behavior

Expected to run a Fastify server correctly.

**Comment by marcod1419** [comment]
Seeing the same issue here!

**Comment by galvez** [comment]
Guys, new release will be out with updated docs and examples this weekend!

**Comment by galvez** [comment]
Will keep this thread open until the announcement :)

**Comment by galvez** [comment]
Closing this as the React examples in v3 release are all working now!
