### ISSUE TITLE
MergeStream dependency not uaed

### ISSUE THREAD

**Issue by Immortalin** [fastify/fastify-vite#77]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

https://github.com/fastify/fastify-vite/blob/0e67daaa5ef8f785ff1fa4b2d170653722360be7/examples/vue-streaming/server.js#L4

**Comment by galvez** [comment]
This code is not ready yet, it's WIP. Please ignore for now!
