### ISSUE TITLE
upgrade to fastify 4

### ISSUE THREAD

**Issue by stregouet** [fastify/fastify-vite#82]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

hi,
first thanks for this good idea of bringing fastify and vite together!
I'm wondering if there is any reason to use fastify 3 instead of fastify 4? I'm just starting a new project with fastify-vite and it seems easier for me to migrate now than later ;)

please tell me if you need any help for this migration! I'm definetly not a fastify expert, but I can try to help.

**Comment by Fdawgs** [comment]
Supported added in [v3](https://github.com/fastify/fastify-vite/releases/tag/v3.0.0)
